version: '2'

services:

  vtigercrm:
    build:
      context: ./docker/
      dockerfile: Dockerfile-vtigercrm
    volumes:
    - .:/var/www/html:rw
    ports:
    - "10777:80"
    links:
    - mysql
    restart: "no"

  mysql:
    image: mysql:5.5
    environment:
    - MYSQL_ROOT_PASSWORD=b016f48d898c745be5ef382254224582
    - MYSQL_DATABASE=vtigercrm
    - MYSQL_USER=vtigercrm
    - MYSQL_PASSWORD=b016f48d898c745be5ef382254224582
    volumes:
    - ./devops/mysql/volume:/var/lib/mysql:rw
    - ./devops/mysql/dumps:/dumps:rw
    restart: "no"

  adminer:
    image: adminer
    ports:
    - "10778:8080"
    links:
    - mysql
